### ISSUE TITLE
The temperature reading is not descriptive enough

### ISSUE THREAD

**Issue by herbotron** [herbotron/coffeebot#7]
**Steps to reproduce**

1. Call coffeebot with "temperature"

**Expected outcome**
Coffeebot should return the following descriptions for these temperature ranges:

- \>24: its toasty
- 23-24: its ok
- 22: its cold
- 21: its very cold
- <20: its fuckin cold

**Actual outcome**
Coffeebot only shows the temperature reading.

Please do the needful asap.

**Comment by cperriam** [comment]
Hi HJ, according to the [coffeebot style guide](https://i.redd.it/j9oljjtf1w6y.jpg), visual imagery should be used in the bots responses where possible.

Can you please attach suitable media (preferably in GIF format) for each of the proposed responses above?

**Comment by herbotron** [comment]
Apologies for the delay, I had to get them UX reviewed.

![t-toasty](https://cloud.githubusercontent.com/assets/26482831/24185681/580609f8-0f39-11e7-845d-36aaf6d52522.gif)
![t-ok](https://cloud.githubusercontent.com/assets/26482831/24185682/5807c824-0f39-11e7-8530-2d3df52dd31b.gif)
![t-cold](https://cloud.githubusercontent.com/assets/26482831/24185679/57f9c242-0f39-11e7-8bcd-fcd969e14c04.gif)
![t-vcold](https://cloud.githubusercontent.com/assets/26482831/24185683/58084fd8-0f39-11e7-9667-c0d60dcf4dc5.gif)
![t-fcold](https://cloud.githubusercontent.com/assets/26482831/24185680/57fe10ea-0f39-11e7-9d85-79a1d9d7cd26.gif)

**Comment by cperriam** [comment]
Raised a pull request for review
[https://github.com/herbotron/coffeebot/pull/9](https://github.com/herbotron/coffeebot/pull/9)
